### ISSUE TITLE
PDF version for CB schematics ?

### ISSUE THREAD

**Issue by barchstien** [proficnc/pixhawk2.1#4]
Hi

I've seen PDF version of schematics for IMU and PSM, but not for CB
Could you add that ?

Thanks
Bastien

**Comment by geekness** [comment]
I too would like a schematic of the carrier board.

**Comment by geekness** [comment]
I found the Schematic for the carrier board here
https://github.com/OpenSolo/Pixhawk_OS_Hardware

I don't think that's the right place for it, as it's not the carrier board on the Solo.
I'd like to find the carrier board schematic for the solo too.

**Comment by andrewbostaph** [comment]
Same, I would like to see the schematics of both the solo and the proficnc pixhawk 2.1 carrier boards

**Comment by proficnc** [comment]
The Solo carrier board is not open. 
The licence on the Carrier board is CC-0
So there is no requirement for it to be published. 
3DR are free to publish it if they wish.
