### ISSUE TITLE
I2C2 Physical Port not working

### ISSUE THREAD

**Issue by theshteff** [proficnc/pixhawk2.1#7]
Possible driver issue on board. Physical I2C2 port not responding. Tested with multiple PixHawk 2.1 units running plane 3.8.3. Multiple I2C devices tested - example Bask Aerospace 4525DO Digital Airspeed Sensor (http://baskaerospace.com.au/store/sensors/pixhawk2-digital-airspeed-sensor/). Problem discussed on DIYDRONES (http://diydrones.com/group/pixhawk2/forum/topics/pixhawk-2-1-issue-with-i2c2-port) and temporary workaround is to splice into GPS cable to access I2C.

**Comment by proficnc** [comment]
Thanks for raising the issue!

**Comment by alexbennett** [comment]
Was this confirmed? The forum post seems inconclusive.

**Comment by proficnc** [comment]
this was proven not to be an issue.
